/* empty css                      */import{S as p,N as h,A as w}from"./assets/vendor-D7M8BDcB.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function u(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=u(e);fetch(e.href,t)}})();new p(".gallery-swiper",{modules:[h,w],loop:!0,speed:600,slidesPerView:1.7,spaceBetween:16,autoplay:{delay:2500,disableOnInteraction:!1},navigation:{nextEl:".gallery-next",prevEl:".gallery-prev"},breakpoints:{1440:{slidesPerView:6,spaceBetween:24}}});let f=null;function g(){window.innerWidth<1440&&!f&&(f=new p(".reviews-swiper",{modules:[w],loop:!0,speed:800,slidesPerView:1,spaceBetween:16,autoplay:{delay:2500,disableOnInteraction:!1}})),window.innerWidth>=1440&&f&&(f.destroy(!0,!0),f=null)}g();window.addEventListener("resize",g);document.addEventListener("DOMContentLoaded",()=>{const c=document.querySelector(".menu-button"),s=c.querySelector(".icon"),u=document.querySelector(".modal"),a=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const l=`
<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M6 36V33H42V36H6ZM6 25.5V22.5H42V25.5H6ZM6 15V12H42V15H6Z" fill="#27221E" />
</svg>
    `,n=`
<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M12.8 38L10 35.2L21.2 24L10 12.8L12.8 10L24 21.2L35.2 10L38 12.8L26.8 24L38 35.2L35.2 38L24 26.8L12.8 38Z" fill="#D871E6" />
</svg>
    `;c.addEventListener("click",()=>{t=!t,s.innerHTML=t?n:l,t?o():i()}),a.forEach(d=>d.addEventListener("click",()=>{i(),s.innerHTML=l,t=!1})),window.addEventListener("scroll",r);function o(){u.style.display="block"}function i(){u.style.display="none"}function r(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function c(){const n=document.getElementById("site-header");return n?n.offsetHeight:0}function s(n){const o=document.getElementById(n);if(!o)return;const i=c(),r=o.getBoundingClientRect().top+window.pageYOffset-i;window.scrollTo({top:r,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(n=>{n.addEventListener("click",function(o){const i=this.getAttribute("href");if(!i)return;const[r,d]=i.split("#");if(!d)return;const m=window.location.pathname.split("/").pop();!(r===""||r==="./"||r===m||r==="./"+m)||!document.getElementById(d)||(o.preventDefault(),s(d),t(d))})});const a=document.querySelectorAll("section[id]"),e=document.querySelectorAll(".navigation-item");function t(n){e.forEach(i=>i.classList.remove("active"));const o=document.querySelector(`.navigation-item a[href*="#${n}"]`);o&&o.closest(".navigation-item").classList.add("active")}function l(){const n=window.pageYOffset+c()+100;a.forEach(o=>{const i=o.offsetTop,r=i+o.offsetHeight;n>=i&&n<r&&t(o.id)})}if(window.addEventListener("scroll",l),window.location.hash){const n=window.location.hash.substring(1);setTimeout(()=>{s(n),t(n)},300)}});
//# sourceMappingURL=index.js.map
